export const cssQuestionsData = [
    {
      id: 0,
      question: "Which CSS property controls the text color?",
      description: null,
      answers: {
        a: "font-color",
        b: "text-color",
        c: "color",
        d: "foreground-color",
      },
      correct_answer: "c",
      explanation: "`color` property sets the text color in CSS.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 1,
      question: "Which CSS property is used to change the background color?",
      description: null,
      answers: {
        a: "background-style",
        b: "background-color",
        c: "bgcolor",
        d: "color-background",
      },
      correct_answer: "b",
      explanation: "`background-color` sets the background color of an element.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 2,
      question: "What does CSS stand for?",
      description: null,
      answers: {
        a: "Creative Style Sheets",
        b: "Cascading Style Sheets",
        c: "Colorful Style Sheets",
        d: "Computer Style Sheets",
      },
      correct_answer: "b",
      explanation: "CSS stands for Cascading Style Sheets.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 3,
      question: "Which CSS property controls the size of the text?",
      description: null,
      answers: {
        a: "font-style",
        b: "text-style",
        c: "font-size",
        d: "text-size",
      },
      correct_answer: "c",
      explanation: "`font-size` defines the size of the text.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 4,
      question: "Which CSS property is used to make text bold?",
      description: null,
      answers: {
        a: "font-weight",
        b: "text-bold",
        c: "bold",
        d: "font-bold",
      },
      correct_answer: "a",
      explanation: "`font-weight` controls the boldness of the text.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 5,
      question: "How do you make a list not display bullet points?",
      description: null,
      answers: {
        a: "list: none;",
        b: "bullet: off;",
        c: "list-style: none;",
        d: "text-decoration: none;",
      },
      correct_answer: "c",
      explanation: "`list-style: none;` removes bullet points from lists.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 6,
      question: "Which property is used to set the spacing between lines of text?",
      description: null,
      answers: {
        a: "line-height",
        b: "spacing",
        c: "line-spacing",
        d: "text-height",
      },
      correct_answer: "a",
      explanation: "`line-height` defines the vertical spacing between lines of text.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 7,
      question: "Which CSS property is used to change the font of an element?",
      description: null,
      answers: {
        a: "font-family",
        b: "font-style",
        c: "text-font",
        d: "font-type",
      },
      correct_answer: "a",
      explanation: "`font-family` sets the font of an element.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 8,
      question: "What symbol is used to select a class in CSS?",
      description: null,
      answers: {
        a: "#",
        b: ".",
        c: "*",
        d: "@",
      },
      correct_answer: "b",
      explanation: "A dot (`.`) is used to select classes in CSS.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 9,
      question: "What symbol is used to select an ID in CSS?",
      description: null,
      answers: {
        a: ".",
        b: "@",
        c: "#",
        d: "%",
      },
      correct_answer: "c",
      explanation: "A hash (`#`) is used to select IDs in CSS.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 10,
      question: "Which CSS property is used to add shadows to text?",
      description: null,
      answers: {
        a: "text-shadow",
        b: "text-decoration",
        c: "font-shadow",
        d: "shadow-text",
      },
      correct_answer: "a",
      explanation: "`text-shadow` adds shadow effects to text.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 11,
      question: "Which property is used to change the left margin of an element?",
      description: null,
      answers: {
        a: "indent",
        b: "padding-left",
        c: "margin-left",
        d: "spacing-left",
      },
      correct_answer: "c",
      explanation: "`margin-left` controls the space on the left side of an element.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 12,
      question: "Which CSS property specifies the space between the element's border and its content?",
      description: null,
      answers: {
        a: "padding",
        b: "margin",
        c: "spacing",
        d: "border-spacing",
      },
      correct_answer: "a",
      explanation: "`padding` controls the space between the content and the border.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 13,
      question: "Which value of the position property makes an element stay relative to the viewport?",
      description: null,
      answers: {
        a: "static",
        b: "relative",
        c: "fixed",
        d: "absolute",
      },
      correct_answer: "c",
      explanation: "`fixed` positioning makes the element stay relative to the viewport.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 14,
      question: "Which property is used to control the order of overlapping elements?",
      description: null,
      answers: {
        a: "overlap",
        b: "z-index",
        c: "stack-order",
        d: "position",
      },
      correct_answer: "b",
      explanation: "`z-index` specifies the stack order of elements.",
      difficulty: "Medium",
      category: "CSS",
      multiple_correct: false,
    },
  ];
  