export const htmlQuestionsData = [
    {
      id: 0,
      question: "Which HTML tag is used to create a line break?",
      description: null,
      answers: {
        a: "<break>",
        b: "<br>",
        c: "<lb>",
        d: "<newline>",
      },
      correct_answer: "b",
      explanation: "`<br>` tag inserts a line break in HTML.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 1,
      question: "Which HTML element defines the title of a document?",
      description: null,
      answers: {
        a: "<head>",
        b: "<meta>",
        c: "<title>",
        d: "<header>",
      },
      correct_answer: "c",
      explanation: "`<title>` sets the document's title shown in browser tabs.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 2,
      question: "What is the correct HTML element for inserting an image?",
      description: null,
      answers: {
        a: "<pic>",
        b: "<image>",
        c: "<img>",
        d: "<src>",
      },
      correct_answer: "c",
      explanation: "`<img>` is used to embed images in HTML.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 3,
      question: "How can you make a numbered list in HTML?",
      description: null,
      answers: {
        a: "<ul>",
        b: "<ol>",
        c: "<dl>",
        d: "<list>",
      },
      correct_answer: "b",
      explanation: "`<ol>` creates an ordered (numbered) list.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 4,
      question: "Which attribute is used to specify a unique identifier for an HTML element?",
      description: null,
      answers: {
        a: "class",
        b: "id",
        c: "key",
        d: "ref",
      },
      correct_answer: "b",
      explanation: "`id` is used to specify a unique identifier.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 5,
      question: "Which tag is used to define an unordered list in HTML?",
      description: null,
      answers: {
        a: "<list>",
        b: "<ol>",
        c: "<ul>",
        d: "<li>",
      },
      correct_answer: "c",
      explanation: "`<ul>` creates an unordered (bulleted) list.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 6,
      question: "How do you create a checkbox in HTML?",
      description: null,
      answers: {
        a: "<input type='checkbox'>",
        b: "<checkbox>",
        c: "<input type='check'>",
        d: "<check>",
      },
      correct_answer: "a",
      explanation: "`<input type='checkbox'>` creates a checkbox input.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 7,
      question: "Which HTML tag is used to create a drop-down list?",
      description: null,
      answers: {
        a: "<input>",
        b: "<select>",
        c: "<dropdown>",
        d: "<list>",
      },
      correct_answer: "b",
      explanation: "`<select>` is used to create a drop-down list.",
      difficulty: "Medium",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 8,
      question: "Which attribute is used to provide an alternate text for an image?",
      description: null,
      answers: {
        a: "alt",
        b: "src",
        c: "title",
        d: "href",
      },
      correct_answer: "a",
      explanation: "`alt` attribute specifies alternative text for images.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 9,
      question: "Which tag is used to define a table row in HTML?",
      description: null,
      answers: {
        a: "<th>",
        b: "<tr>",
        c: "<td>",
        d: "<table>",
      },
      correct_answer: "b",
      explanation: "`<tr>` defines a table row.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 10,
      question: "Which tag is used to define a table cell in HTML?",
      description: null,
      answers: {
        a: "<tr>",
        b: "<table>",
        c: "<td>",
        d: "<th>",
      },
      correct_answer: "c",
      explanation: "`<td>` defines a standard cell inside a table.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 11,
      question: "Which HTML element defines emphasized text?",
      description: null,
      answers: {
        a: "<em>",
        b: "<i>",
        c: "<strong>",
        d: "<mark>",
      },
      correct_answer: "a",
      explanation: "`<em>` is used to emphasize text.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 12,
      question: "Which doctype is correct for HTML5?",
      description: null,
      answers: {
        a: "<!DOCTYPE html>",
        b: "<!DOCTYPE HTML PUBLIC>",
        c: "<!DOCTYPE HTML5>",
        d: "<html>",
      },
      correct_answer: "a",
      explanation: "`<!DOCTYPE html>` declares an HTML5 document.",
      difficulty: "Medium",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 13,
      question: "Which HTML element is used to play video files?",
      description: null,
      answers: {
        a: "<media>",
        b: "<video>",
        c: "<movie>",
        d: "<play>",
      },
      correct_answer: "b",
      explanation: "`<video>` is used to embed video content in HTML.",
      difficulty: "Medium",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 14,
      question: "Which HTML tag is used to mark up a quotation?",
      description: null,
      answers: {
        a: "<quote>",
        b: "<q>",
        c: "<blockquote>",
        d: "<cite>",
      },
      correct_answer: "b",
      explanation: "`<q>` is used for short inline quotations.",
      difficulty: "Medium",
      category: "HTML",
      multiple_correct: false,
    },
  ];
  