export const javascriptQuestionsData = [
  {
    id: 0,
    question: "Which keyword is used to declare a variable in JavaScript?",
    description: null,
    answers: {
      a: "var",
      b: "int",
      c: "let",
      d: "both a and c",
    },
    correct_answer: "d",
    explanation:
      "`var` and `let` are both used to declare variables in JavaScript.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 1,
    question: "Which company developed JavaScript?",
    description: null,
    answers: {
      a: "Microsoft",
      b: "Sun Microsystems",
      c: "Netscape",
      d: "Oracle",
    },
    correct_answer: "c",
    explanation: "Netscape developed JavaScript in 1995.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 2,
    question: "Inside which HTML element do we put JavaScript code?",
    description: null,
    answers: {
      a: "<js>",
      b: "<scripting>",
      c: "<javascript>",
      d: "<script>",
    },
    correct_answer: "d",
    explanation: "`<script>` tag is used to embed JavaScript into HTML.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 3,
    question: "Which symbol is used for comments in JavaScript?",
    description: null,
    answers: {
      a: "//",
      b: "/* */",
      c: "<!-- -->",
      d: "both a and b",
    },
    correct_answer: "d",
    explanation: "`//` for single-line and `/* */` for multi-line comments.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 4,
    question: "How do you create a function in JavaScript?",
    description: null,
    answers: {
      a: "function = myFunction()",
      b: "function myFunction()",
      c: "function:myFunction()",
      d: "create myFunction()",
    },
    correct_answer: "b",
    explanation: "`function myFunction()` is the correct syntax.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 5,
    question: "Which operator is used to assign a value to a variable?",
    description: null,
    answers: {
      a: "*",
      b: "-",
      c: "=",
      d: "+",
    },
    correct_answer: "c",
    explanation: "`=` assigns a value to a variable.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 6,
    question: "How do you call a function named `myFunction`?",
    description: null,
    answers: {
      a: "call myFunction()",
      b: "myFunction()",
      c: "call function myFunction",
      d: "Call.myFunction()",
    },
    correct_answer: "b",
    explanation:
      "Functions are called by using their name followed by parentheses.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 7,
    question:
      "Which built-in method combines the text of two strings and returns a new string?",
    description: null,
    answers: {
      a: "append()",
      b: "concat()",
      c: "attach()",
      d: "combine()",
    },
    correct_answer: "b",
    explanation: "`concat()` joins two or more strings.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 8,
    question:
      "How can you add a comment in JavaScript that spans multiple lines?",
    description: null,
    answers: {
      a: "// This is a comment",
      b: "/* This is a comment */",
      c: "<!-- This is a comment -->",
      d: "** This is a comment **",
    },
    correct_answer: "b",
    explanation: "`/* */` is used for multi-line comments.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 9,
    question: "Which of the following is a JavaScript data type?",
    description: null,
    answers: {
      a: "Number",
      b: "String",
      c: "Boolean",
      d: "All of the above",
    },
    correct_answer: "d",
    explanation: "Number, String, and Boolean are all JavaScript data types.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 10,
    question:
      "What is the correct syntax for referring to an external script called 'xxx.js'?",
    description: null,
    answers: {
      a: "<script href='xxx.js'>",
      b: "<script src='xxx.js'>",
      c: "<script name='xxx.js'>",
      d: "<script file='xxx.js'>",
    },
    correct_answer: "b",
    explanation:
      "Use `src` attribute to reference an external JavaScript file.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 11,
    question: "How do you write 'Hello World' in an alert box?",
    description: null,
    answers: {
      a: "msg('Hello World');",
      b: "alertBox('Hello World');",
      c: "msgBox('Hello World');",
      d: "alert('Hello World');",
    },
    correct_answer: "d",
    explanation: "`alert()` is used to show popup alerts.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 12,
    question: "How do you create an array in JavaScript?",
    description: null,
    answers: {
      a: "var arr = (1,2,3);",
      b: "var arr = [1,2,3];",
      c: "var arr = {1,2,3};",
      d: "var arr = '1,2,3';",
    },
    correct_answer: "b",
    explanation: "Arrays are created using square brackets `[]`.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 13,
    question: "Which method is used to find the length of a string?",
    description: null,
    answers: {
      a: "length()",
      b: "size()",
      c: "length",
      d: "count()",
    },
    correct_answer: "c",
    explanation: "Use `.length` property to find the string length.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 14,
    question: "Which keyword is used to exit a loop in JavaScript?",
    description: null,
    answers: {
      a: "stop",
      b: "exit",
      c: "break",
      d: "return",
    },
    correct_answer: "c",
    explanation: "`break` statement exits the loop immediately.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 15,
    question: "How do you round the number 7.25 to the nearest integer?",
    description: null,
    answers: {
      a: "Math.rnd(7.25)",
      b: "Math.round(7.25)",
      c: "round(7.25)",
      d: "Math.floor(7.25)",
    },
    correct_answer: "b",
    explanation: "Use `Math.round()` to round to the nearest integer.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 16,
    question: "Which method adds a new element at the end of an array?",
    description: null,
    answers: {
      a: "push()",
      b: "pop()",
      c: "shift()",
      d: "unshift()",
    },
    correct_answer: "a",
    explanation: "`push()` adds an item to the end of the array.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 17,
    question: "Which method removes the last element from an array?",
    description: null,
    answers: {
      a: "shift()",
      b: "pop()",
      c: "remove()",
      d: "delete()",
    },
    correct_answer: "b",
    explanation: "`pop()` removes the last item from an array.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 18,
    question: "Which operator is used to compare both value and type?",
    description: null,
    answers: {
      a: "==",
      b: "=",
      c: "===",
      d: "!=",
    },
    correct_answer: "c",
    explanation: "`===` checks both value and type.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 19,
    question: "Which function converts a string to an integer in JavaScript?",
    description: null,
    answers: {
      a: "parseInt()",
      b: "parseFloat()",
      c: "toString()",
      d: "Number()",
    },
    correct_answer: "a",
    explanation: "`parseInt()` parses a string and returns an integer.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 20,
    question: "Which method can be used to select an HTML element by ID?",
    description: null,
    answers: {
      a: "getElementByClassName",
      b: "getElementById",
      c: "querySelectorAll",
      d: "querySelectorAllId",
    },
    correct_answer: "b",
    explanation: "`getElementById` selects an element with a specific ID.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 21,
    question: "What does JSON stand for?",
    description: null,
    answers: {
      a: "Java Standard Output Network",
      b: "JavaScript Object Notation",
      c: "Java Source Open Network",
      d: "Just Short Object Notation",
    },
    correct_answer: "b",
    explanation: "JSON stands for JavaScript Object Notation.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 22,
    question: "Which method parses a JSON string into a JavaScript object?",
    description: null,
    answers: {
      a: "JSON.parse()",
      b: "JSON.stringify()",
      c: "JSON.convert()",
      d: "JSON.toObject()",
    },
    correct_answer: "a",
    explanation: "`JSON.parse()` parses a JSON string into an object.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 23,
    question: "How do you write a conditional (if) statement in JavaScript?",
    description: null,
    answers: {
      a: "if i = 5",
      b: "if i == 5 then",
      c: "if (i == 5)",
      d: "if i = 5 then",
    },
    correct_answer: "c",
    explanation:
      "JavaScript conditional statements use `if (condition) {}` syntax.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 24,
    question: "Which loop is guaranteed to run at least once?",
    description: null,
    answers: {
      a: "for",
      b: "while",
      c: "do...while",
      d: "foreach",
    },
    correct_answer: "c",
    explanation:
      "`do...while` loop runs the code block once before checking condition.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 25,
    question: "How do you access the first element of an array called `arr`?",
    description: null,
    answers: {
      a: "arr[0]",
      b: "arr(0)",
      c: "arr{0}",
      d: "arr.0",
    },
    correct_answer: "a",
    explanation:
      "Array elements are accessed using bracket notation with index 0.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 26,
    question: "Which keyword is used to define a constant in JavaScript?",
    description: null,
    answers: {
      a: "let",
      b: "var",
      c: "const",
      d: "constant",
    },
    correct_answer: "c",
    explanation: "`const` is used to declare constants.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 27,
    question: "Which event occurs when the user clicks on an HTML element?",
    description: null,
    answers: {
      a: "onmouseover",
      b: "onchange",
      c: "onclick",
      d: "onmouseclick",
    },
    correct_answer: "c",
    explanation: "`onclick` event triggers when an element is clicked.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 28,
    question: "What is the correct way to write a JavaScript array?",
    description: null,
    answers: {
      a: "var colors = 'red', 'green', 'blue'",
      b: "var colors = (1:'red', 2:'green', 3:'blue')",
      c: "var colors = ['red', 'green', 'blue']",
      d: "var colors = 1=('red'), 2=('green'), 3=('blue')",
    },
    correct_answer: "c",
    explanation: "JavaScript arrays are declared using square brackets.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 29,
    question: "How do you check the type of a variable?",
    description: null,
    answers: {
      a: "typeof",
      b: "typeOf",
      c: "checkType",
      d: "varType",
    },
    correct_answer: "a",
    explanation: "`typeof` operator returns the type of a variable.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 30,
    question: "Which built-in method calls a function for each element in an array?",
    description: null,
    answers: {
      a: "while()",
      b: "loop()",
      c: "forEach()",
      d: "each()",
    },
    correct_answer: "c",
    explanation: "`forEach()` calls a function for each array element.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 31,
    question: "Which of the following is a JavaScript framework?",
    description: null,
    answers: {
      a: "Django",
      b: "Laravel",
      c: "React",
      d: "Rails",
    },
    correct_answer: "c",
    explanation: "`React` is a JavaScript library for building user interfaces.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 32,
    question: "Which symbol is used for comments in JavaScript?",
    description: null,
    answers: {
      a: "//",
      b: "/*",
      c: "<!--",
      d: "**",
    },
    correct_answer: "a",
    explanation: "`//` is used for single-line comments in JavaScript.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 33,
    question: "How do you declare a JavaScript variable?",
    description: null,
    answers: {
      a: "v myVariable;",
      b: "variable myVariable;",
      c: "var myVariable;",
      d: "myVariable var;",
    },
    correct_answer: "c",
    explanation: "`var`, `let`, or `const` are used to declare variables.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 34,
    question: "Which company developed JavaScript?",
    description: null,
    answers: {
      a: "Mozilla",
      b: "Netscape",
      c: "Microsoft",
      d: "Oracle",
    },
    correct_answer: "b",
    explanation: "JavaScript was developed by Netscape Communications.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 35,
    question: "Which of the following is NOT a JavaScript data type?",
    description: null,
    answers: {
      a: "Number",
      b: "Boolean",
      c: "Float",
      d: "String",
    },
    correct_answer: "c",
    explanation: "JavaScript has Number type, but not a separate Float type.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 36,
    question: "Which method joins two or more arrays?",
    description: null,
    answers: {
      a: "append()",
      b: "merge()",
      c: "concat()",
      d: "attach()",
    },
    correct_answer: "c",
    explanation: "`concat()` merges two or more arrays.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 37,
    question: "How can you convert a string to lowercase in JavaScript?",
    description: null,
    answers: {
      a: "toLowerCase()",
      b: "lowerCase()",
      c: "convertLower()",
      d: "toLower()",
    },
    correct_answer: "a",
    explanation: "`toLowerCase()` method converts string to lowercase.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 38,
    question: "Which method returns the character at a specified index?",
    description: null,
    answers: {
      a: "charAt()",
      b: "charAtIndex()",
      c: "characterAt()",
      d: "getChar()",
    },
    correct_answer: "a",
    explanation: "`charAt(index)` returns the character at the specified index.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 39,
    question: "Which of the following is the correct way to create a function in JavaScript?",
    description: null,
    answers: {
      a: "function:myFunction()",
      b: "function = myFunction()",
      c: "function myFunction()",
      d: "create function myFunction()",
    },
    correct_answer: "c",
    explanation: "`function myFunction() {}` is the correct syntax.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 40,
    question: "Which method adds one or more elements to the beginning of an array?",
    description: null,
    answers: {
      a: "push()",
      b: "pop()",
      c: "unshift()",
      d: "shift()",
    },
    correct_answer: "c",
    explanation: "`unshift()` adds elements to the start of an array.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 41,
    question: "Which JavaScript keyword is used to define an asynchronous function?",
    description: null,
    answers: {
      a: "async",
      b: "await",
      c: "setTimeout",
      d: "promise",
    },
    correct_answer: "a",
    explanation: "`async` defines an asynchronous function.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 42,
    question: "Which object is the parent of all JavaScript objects?",
    description: null,
    answers: {
      a: "Array",
      b: "Function",
      c: "Object",
      d: "String",
    },
    correct_answer: "c",
    explanation: "All objects in JavaScript inherit from `Object`.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 43,
    question: "What is the default value of an uninitialized variable?",
    description: null,
    answers: {
      a: "0",
      b: "null",
      c: "undefined",
      d: "false",
    },
    correct_answer: "c",
    explanation: "Uninitialized variables are `undefined`.",
    difficulty: "Easy",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 44,
    question: "Which JavaScript method is used to filter an array?",
    description: null,
    answers: {
      a: "filter()",
      b: "find()",
      c: "select()",
      d: "match()",
    },
    correct_answer: "a",
    explanation: "`filter()` creates a new array with all elements that pass the test.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 45,
    question: "How do you stop an interval timer in JavaScript?",
    description: null,
    answers: {
      a: "clearInterval()",
      b: "clearTimeout()",
      c: "stopInterval()",
      d: "cancelInterval()",
    },
    correct_answer: "a",
    explanation: "`clearInterval()` stops an interval timer.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 46,
    question: "What keyword is used to handle exceptions in JavaScript?",
    description: null,
    answers: {
      a: "catch",
      b: "throw",
      c: "try",
      d: "error",
    },
    correct_answer: "c",
    explanation: "`try` is used to handle exceptions.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 47,
    question: "What is the output of '2' + 2 in JavaScript?",
    description: null,
    answers: {
      a: "4",
      b: "22",
      c: "NaN",
      d: "undefined",
    },
    correct_answer: "b",
    explanation: "When adding a string and a number, JavaScript concatenates the result into a string.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 48,
    question: "Which function is used to delay code execution?",
    description: null,
    answers: {
      a: "setInterval()",
      b: "setTimeout()",
      c: "delay()",
      d: "pause()",
    },
    correct_answer: "b",
    explanation: "`setTimeout()` is used to delay execution.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },
  {
    id: 49,
    question: "What will be the output of typeof NaN?",
    description: null,
    answers: {
      a: "number",
      b: "NaN",
      c: "undefined",
      d: "object",
    },
    correct_answer: "a",
    explanation: "`typeof NaN` returns `number` because NaN is considered a numeric value.",
    difficulty: "Medium",
    category: "JavaScript",
    multiple_correct: false,
  },

];
