export const questionsData = [
    {
      id: 0,
      question: "Which language runs in a web browser?",
      description: "Choose the correct scripting language.",
      answers: {
        a: "Java",
        b: "C",
        c: "Python",
        d: "JavaScript",
      },
      correct_answer: "d",
      explanation: "JavaScript is designed to run in browsers.",
      difficulty: "Easy",
      category: "Programming",
      multiple_correct: false,
    },
    {
      id: 1,
      question: "What is the command to initialize a git repository?",
      description: null,
      answers: {
        a: "git start",
        b: "git init",
        c: "git push",
        d: "git clone",
      },
      correct_answer: "b",
      explanation: "`git init` creates a new Git repo.",
      difficulty: "Medium",
      category: "Git",
      multiple_correct: false,
    },
    {
      id: 2,
      question: "Which HTML tag is used to define a hyperlink?",
      description: null,
      answers: {
        a: "<a>",
        b: "<link>",
        c: "<href>",
        d: "<hyperlink>",
      },
      correct_answer: "a",
      explanation: "The `<a>` tag defines a hyperlink.",
      difficulty: "Easy",
      category: "HTML",
      multiple_correct: false,
    },
    {
      id: 3,
      question: "What does CSS stand for?",
      description: null,
      answers: {
        a: "Colorful Style Sheets",
        b: "Computer Style Sheets",
        c: "Cascading Style Sheets",
        d: "Creative Style Sheets",
      },
      correct_answer: "c",
      explanation: "CSS stands for Cascading Style Sheets.",
      difficulty: "Easy",
      category: "CSS",
      multiple_correct: false,
    },
    {
      id: 4,
      question: "Which method is used to add an element at the end of an array in JavaScript?",
      description: null,
      answers: {
        a: "add()",
        b: "push()",
        c: "append()",
        d: "insert()",
      },
      correct_answer: "b",
      explanation: "The `push()` method adds an item to the end of an array.",
      difficulty: "Easy",
      category: "JavaScript",
      multiple_correct: false,
    },
    // {
    //   id: 6,
    //   question: "What command is used to stage all changed files for the next commit in Git?",
    //   description: null,
    //   answers: {
    //     a: "git push",
    //     b: "git add .",
    //     c: "git commit -m",
    //     d: "git stage",
    //   },
    //   correct_answer: "b",
    //   explanation: "`git add .` stages all modified files.",
    //   difficulty: "Medium",
    //   category: "Git",
    //   multiple_correct: false,
    // },
    // {
    //   id: 7,
    //   question: "Which CSS property controls the text size?",
    //   description: null,
    //   answers: {
    //     a: "font-style",
    //     b: "text-size",
    //     c: "font-size",
    //     d: "text-style",
    //   },
    //   correct_answer: "c",
    //   explanation: "`font-size` sets the size of the text.",
    //   difficulty: "Easy",
    //   category: "CSS",
    //   multiple_correct: false,
    // },
    // {
    //   id: 8,
    //   question: "Which React hook is used for side effects?",
    //   description: null,
    //   answers: {
    //     a: "useState",
    //     b: "useEffect",
    //     c: "useContext",
    //     d: "useReducer",
    //   },
    //   correct_answer: "b",
    //   explanation: "`useEffect` runs side-effect logic in React.",
    //   difficulty: "Medium",
    //   category: "React",
    //   multiple_correct: false,
    // },
    // {
    //   id: 9,
    //   question: "What is the default port number for a React development server?",
    //   description: null,
    //   answers: {
    //     a: "3000",
    //     b: "8000",
    //     c: "5000",
    //     d: "8080",
    //   },
    //   correct_answer: "a",
    //   explanation: "React apps start by default on port 3000.",
    //   difficulty: "Easy",
    //   category: "React",
    //   multiple_correct: false,
    // },
    // {
    //   id: 10,
    //   question: "Which HTML attribute is used to define inline styles?",
    //   description: null,
    //   answers: {
    //     a: "class",
    //     b: "styles",
    //     c: "style",
    //     d: "css",
    //   },
    //   correct_answer: "c",
    //   explanation: "`style` is used for inline CSS in HTML.",
    //   difficulty: "Easy",
    //   category: "HTML",
    //   multiple_correct: false,
    // },
    // {
    //   id: 11,
    //   question: "What keyword is used to declare a constant in JavaScript?",
    //   description: null,
    //   answers: {
    //     a: "var",
    //     b: "const",
    //     c: "let",
    //     d: "constant",
    //   },
    //   correct_answer: "b",
    //   explanation: "`const` declares constants that can't be reassigned.",
    //   difficulty: "Easy",
    //   category: "JavaScript",
    //   multiple_correct: false,
    // },
    // {
    //   id: 12,
    //   question: "Which git command is used to download a project from a remote repo?",
    //   description: null,
    //   answers: {
    //     a: "git pull",
    //     b: "git push",
    //     c: "git clone",
    //     d: "git init",
    //   },
    //   correct_answer: "c",
    //   explanation: "`git clone` copies a repo to your local machine.",
    //   difficulty: "Medium",
    //   category: "Git",
    //   multiple_correct: false,
    // },
    // {
    //   id: 13,
    //   question: "What does JSX stand for in React?",
    //   description: null,
    //   answers: {
    //     a: "Java Syntax Extension",
    //     b: "JavaScript XML",
    //     c: "JavaScript Extension",
    //     d: "Java Styled XML",
    //   },
    //   correct_answer: "b",
    //   explanation: "JSX stands for JavaScript XML, used to write HTML in React.",
    //   difficulty: "Medium",
    //   category: "React",
    //   multiple_correct: false,
    // },
    // {
    //   id: 14,
    //   question: "How do you write a comment in JavaScript?",
    //   description: null,
    //   answers: {
    //     a: "# This is a comment",
    //     b: "/* This is a comment */",
    //     c: "// This is a comment",
    //     d: "<!-- This is a comment -->",
    //   },
    //   correct_answer: "c",
    //   explanation: "`//` is used for single-line comments in JavaScript.",
    //   difficulty: "Easy",
    //   category: "JavaScript",
    //   multiple_correct: false,
    // },
    // {
    //   id: 15,
    //   question: "Which HTML tag is used to display a table?",
    //   description: null,
    //   answers: {
    //     a: "<table>",
    //     b: "<list>",
    //     c: "<ul>",
    //     d: "<tab>",
    //   },
    //   correct_answer: "a",
    //   explanation: "`<table>` defines a table in HTML.",
    //   difficulty: "Easy",
    //   category: "HTML",
    //   multiple_correct: false,
    // }
  ];
  